#!/bin/bash

if [ $# -ne 2 ]; then
        echo "Faltan parametros [host] [carpeta]"
        exit 1
fi

rsync -avvhpzrP --rsh=ssh root@$1.cat1.net:/backup/cpbackup/$2 /backup/$1 > /backup/rsync-$1-$2-log

#cat /backup/rsync-$1-$2-log | mail -s "rsync-$1-$2-log" root
strings /backup/rsync-$1-$2-log | grep -v -P '(?!.*xfer)/s ' | mail -s "rsync-$1-$2-log" root

exit 0