#!/bin/bash
# *************************************************************************
# Proceso bash para automatizar la creación de copias de respaldo completas 
# de las cuentas de CPanel del servidor.  
#
# Se puede llamar vía cron, por ejemplo:
# 35 4 * * * /scripts/fullback 2>&1 | tee /var/logs/fullback.log
# *************************************************************************

IFS="$"

HORA_MAXIMA=4
DIAS_MAXIMO=30
LOAD_MAXIMO=5
SEGUNDOS_ESPERA=120

HOST=$(uname -n)

echo "$HOST inicio proceso a las $(date +"%H:%M:%S")"

if [ $# -eq 3 ]; then
        if [ "OldsTo" = "$1" ]; then
                MHOST=$2
                MPATH=$3
                echo "los backups antiguos van a $MHOST.cat1.net carpeta /backup/$MPATH/"
        fi
fi

cd /home

ls /var/cpanel/users | grep -v "root\|mysql\|nobody" | while read CPUSER; do

        load=1

        until [ "$load" == "0" ]
        do
                # comprobar hora
                hora=$(date +%H)
                if [ $hora -gt $HORA_MAXIMA ]
                then
                        echo "paso la hora maxima (las $HORA_MAXIMA h)!!!"
                        exit 1
                fi

                # comprobar load
                l15="$(uptime |awk -F'average:' '{ print $2}' | sed s/,//g | awk '{ print $2}')"
                load="$(echo "$l15 >= $LOAD_MAXIMO" | bc)"
                if [ "$load" == "1" ]
                then
                        echo "load $l15 >= $LOAD_MAXIMO  esperando $SEGUNDOS_ESPERA segundos..."
                        sleep $SEGUNDOS_ESPERA
                fi

        done

        r=/home/cpmove-${CPUSER}.tar.gz
        if [ -e $r ]
        then
                d=$((($(date +%s) - $(stat -c '%Y' "$r"))/86400))
                if [ $d -lt $DIAS_MAXIMO ]
                then
                        echo "backup ${CPUSER} solo tiene $d dias... continuar con el siguiente"
                        continue
                else
                        if [ -n "$MHOST" ] && [ -n "$MPATH" ]; then
                                echo "copiar backup antiguo $r a $MHOST /backup/$MPATH/"
                                rsync -avvhpzrP --rsh=ssh $r root@$MHOST.cat1.net:/backup/$MPATH/
                        fi                        
                fi
        fi

        echo "$(date +"%H:%M:%S") inicio backup ${CPUSER}"
        /scripts/pkgacct ${CPUSER}
        echo "$(date +"%H:%M:%S") fin backup ${CPUSER}"

done

echo "$HOST fin proceso a las $(date +"%H:%M:%S")"

# strings /var/logs/fullback.log | mail -s "fullback log $HOST" root
exit 0
